apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: gitops
  description: "Criando serviço gitops"
  labels:
    system: web-apps
  tags:
    - terraform
    - gitops
  links:
    - url: https://github.com/github.com?owner=ElananRodrigues&repo=gitops/gitops
      title: Backstage Sample Service GitHub
      icon: code
  annotations:
    opsgenie.com/component-selector: 'tag:"service:gitops"'
    jenkins.io/github-folder: 'github.com?owner=ElananRodrigues&repo=gitops/gitops'
    fossa.io/project-name: backstage-sample-service
    goharbor.io/repository-slug: 'github.com?owner=ElananRodrigues&repo=gitops/gitops'
    github.com/project-slug: 'github.com?owner=ElananRodrigues&repo=gitops/gitops'
    backstage.io/techdocs-ref: dir:.
spec:
  type: service
  lifecycle: experimental
  owner: user:guest